"""initial_create_all_tables

Revision ID: d8f3ae802d7c
Revises: 
Create Date: 2026-06-08 12:06:14.615362
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f3ae802d7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='操作用户 ID'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='操作用户名'),
    sa.Column('action', sa.String(length=200), nullable=False, comment='操作类型'),
    sa.Column('resource', sa.String(length=200), nullable=True, comment='操作资源'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情 (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作 IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('circuit_breakers',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='熔断范围: strategy | account | global'),
    sa.Column('trigger_reason', sa.Text(), nullable=False, comment='触发原因'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True, comment='解除人'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breakers_is_active'), 'circuit_breakers', ['is_active'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_user_id'), 'circuit_breakers', ['user_id'], unique=False)
    op.create_table('funding_rates',
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='结算时间'),
    sa.Column('rate', sa.Numeric(precision=18, scale=10), nullable=False, comment='资金费率'),
    sa.Column('next_rate', sa.Numeric(precision=18, scale=10), nullable=True, comment='预测下一期费率'),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'timestamp')
    )
    op.create_index('idx_funding_symbol_time', 'funding_rates', ['symbol', 'timestamp'], unique=False)
    op.create_table('klines',
    sa.Column('exchange', sa.String(length=20), nullable=False, comment='交易所'),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='交易对'),
    sa.Column('interval', sa.String(length=10), nullable=False, comment='K线周期: 1m/5m/15m/30m/1h/4h/1d/1w'),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False, comment='开盘时间'),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False, comment='成交量(基础币)'),
    sa.Column('quote_volume', sa.Numeric(precision=24, scale=8), nullable=False, comment='成交额(计价币)'),
    sa.Column('trades_count', sa.Integer(), nullable=False, comment='成交笔数'),
    sa.Column('taker_buy_volume', sa.Numeric(precision=24, scale=8), nullable=False, comment='主动买入量'),
    sa.Column('taker_buy_quote_volume', sa.Numeric(precision=24, scale=8), nullable=False, comment='主动买入额'),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'interval', 'open_time')
    )
    op.create_index('idx_klines_exchange_symbol', 'klines', ['exchange', 'symbol', 'interval'], unique=False)
    op.create_index('idx_klines_symbol_interval_time', 'klines', ['symbol', 'interval', 'open_time'], unique=False)
    op.create_table('notification_rules',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('strategy_id', sa.UUID(), nullable=True, comment='策略 ID（空=系统级/价格告警）'),
    sa.Column('rule_type', sa.String(length=30), nullable=False, comment='规则类型: strategy_alert | system_alert | price_alert'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='规则名称'),
    sa.Column('conditions', sa.Text(), nullable=False, comment='触发条件 (JSON)'),
    sa.Column('channels', sa.String(length=500), nullable=False, comment="通知渠道 (JSON): ['in_app','email','telegram','discord','dingtalk']"),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False, comment='冷却时间（秒），防止频繁通知'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_strategy_id'), 'notification_rules', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_notification_rules_user_id'), 'notification_rules', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='接收用户 ID'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='通知标题'),
    sa.Column('body', sa.Text(), nullable=True, comment='通知正文'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='分类: strategy | system | price | risk | account | general'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='严重程度: info | warning | error | critical'),
    sa.Column('channel', sa.String(length=30), nullable=False, comment='送达渠道: in_app | email | telegram | discord | dingtalk'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='快照时间'),
    sa.Column('bids', sa.String(), nullable=False, comment='买盘 (JSON: [[price, qty], ...])'),
    sa.Column('asks', sa.String(), nullable=False, comment='卖盘 (JSON: [[price, qty], ...])'),
    sa.Column('best_bid', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('best_ask', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('spread', sa.Numeric(precision=24, scale=8), nullable=False, comment='买卖价差'),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'timestamp')
    )
    op.create_index('idx_ob_snapshot_symbol_time', 'orderbook_snapshots', ['symbol', 'timestamp'], unique=False)
    op.create_table('risk_events',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('strategy_id', sa.UUID(), nullable=True, comment='策略 ID'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型: stop_loss_triggered | take_profit_triggered | position_liquidated | daily_loss_halt | max_drawdown_halt | global_circuit_breaker'),
    sa.Column('symbol', sa.String(length=50), nullable=True, comment='相关交易对'),
    sa.Column('detail', sa.Text(), nullable=True, comment='事件详情 (JSON)'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='严重程度: info | warning | critical'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_strategy_id'), 'risk_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('strategy_id', sa.UUID(), nullable=True, comment='策略 ID（空=账户级/全局级）'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='作用域: strategy | account | global'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='规则类型: stop_loss | take_profit | trailing_stop | daily_loss_limit | consecutive_loss_limit | max_drawdown | max_position_pct | margin_limit'),
    sa.Column('params', sa.Text(), nullable=False, comment='规则参数 (JSON)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rules_strategy_id'), 'risk_rules', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_risk_rules_user_id'), 'risk_rules', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='角色描述'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限点列表 (JSON)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sim_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False, comment='spot|perpetual'),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('current_equity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('available_cash', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_accounts_user_id'), 'sim_accounts', ['user_id'], unique=False)
    op.create_table('ticker_data',
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('bid', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('ask', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high_24h', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low_24h', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('quote_volume_24h', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('change_pct_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=24, scale=8), nullable=True, comment='未平仓合约量 (合约)'),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='标记价格 (合约)'),
    sa.Column('index_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='指数价格 (合约)'),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'timestamp')
    )
    op.create_index('idx_ticker_symbol_time', 'ticker_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False, comment='通知偏好 (JSON): {category: {channels: [...], quiet_hours: {...}}}'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户 ID'),
    sa.Column('refresh_token', sa.String(length=500), nullable=False, comment='Refresh Token'),
    sa.Column('device_info', sa.String(length=500), nullable=True, comment='设备信息 (User-Agent)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='登录 IP'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='会话是否有效'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt 哈希密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账户是否启用'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='邮箱/手机是否已验证'),
    sa.Column('totp_secret', sa.String(length=255), nullable=True, comment='TOTP 二步验证密钥'),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False, comment='是否已启用 2FA'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='锁定截止时间'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='上次登录时间'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='上次登录 IP'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='交易所 (binance/okx/bybit/gateio)'),
    sa.Column('label', sa.String(length=200), nullable=False, comment='备注名称'),
    sa.Column('access_key', sa.String(length=500), nullable=False, comment='Access Key (AES-256-GCM 加密)'),
    sa.Column('secret_key_encrypted', sa.String(length=1000), nullable=False, comment='Secret Key (AES-256-GCM 加密)'),
    sa.Column('passphrase_encrypted', sa.String(length=500), nullable=True, comment='Passphrase (OKX 需要, AES-256-GCM 加密)'),
    sa.Column('permissions', sa.String(length=200), nullable=True, comment='API 权限: read,trade,withdraw'),
    sa.Column('has_withdraw_permission', sa.Boolean(), nullable=False, comment='是否开启了提币权限'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='上次账户信息同步时间'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('sim_trades',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.ForeignKeyConstraint(['account_id'], ['sim_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_trades_account_id'), 'sim_trades', ['account_id'], unique=False)
    op.create_table('strategies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='策略名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('strategy_type', sa.String(length=20), nullable=False, comment='策略类型: visual | python'),
    sa.Column('definition', sa.Text(), nullable=True, comment='策略定义 (JSON 节点图 或 Python 代码)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='生命周期: draft | backtested | simulated | live | paused | archived'),
    sa.Column('version', sa.Integer(), nullable=False, comment='当前版本号'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签 (JSON 数组)'),
    sa.Column('trade_type', sa.String(length=20), nullable=False, comment='交易类型: spot | perpetual | futures'),
    sa.Column('symbol_pool', sa.Text(), nullable=True, comment='交易对池配置 (JSON)'),
    sa.Column('kline_interval', sa.String(length=10), nullable=False, comment='K线周期: 1m/5m/15m/1h/4h/1d'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除（软删除标记）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('backtest_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('strategy_id', sa.UUID(), nullable=True, comment='策略 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='回测任务名称'),
    sa.Column('symbols', sa.Text(), nullable=False, comment="交易对列表 (JSON): ['BTCUSDT','ETHUSDT']"),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('kline_interval', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='回测开始时间'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='回测结束时间'),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False, comment='初始资金 (USDT)'),
    sa.Column('commission_rate', sa.Float(), nullable=False, comment='手续费率 (Taker 0.04%)'),
    sa.Column('slippage', sa.Float(), nullable=False, comment='滑点 (0.05%)'),
    sa.Column('fill_mode', sa.String(length=20), nullable=False, comment='撮合模式: next_open | close | limit | vwap | counterparty'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | running | completed | failed | cancelled'),
    sa.Column('progress', sa.Float(), nullable=False, comment='进度 (0-100)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_tasks_status'), 'backtest_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_tasks_strategy_id'), 'backtest_tasks', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_tasks_user_id'), 'backtest_tasks', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('strategy_id', sa.UUID(), nullable=True, comment='策略 ID（手动下单则为空）'),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='交易所'),
    sa.Column('exchange_order_id', sa.String(length=200), nullable=True, comment='交易所返回的订单 ID'),
    sa.Column('client_order_id', sa.String(length=100), nullable=True, comment='客户端订单 ID'),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='交易对'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='方向: buy | sell'),
    sa.Column('order_type', sa.String(length=30), nullable=False, comment='类型: market | limit | stop_market | stop_limit | iceberg | twap'),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True, comment='限价（市价单为空）'),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False, comment='数量（基础币）'),
    sa.Column('filled_amount', sa.Numeric(precision=24, scale=8), nullable=False, comment='已成交数量'),
    sa.Column('avg_fill_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='成交均价'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='created | submitted | partially_filled | filled | cancelled | expired | rejected'),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=True, comment='手续费'),
    sa.Column('commission_asset', sa.String(length=20), nullable=True, comment='手续费币种'),
    sa.Column('leverage', sa.Integer(), nullable=True, comment='杠杆倍数'),
    sa.Column('margin_mode', sa.String(length=20), nullable=True, comment='保证金模式: cross | isolated'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('param_optimization_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('param_grid', sa.Text(), nullable=False, comment="参数网格 (JSON): {'ema_fast_period': {'min':5,'max':30,'step':1}, ...}"),
    sa.Column('optimization_method', sa.String(length=30), nullable=False, comment='优化方法: grid_search | bayesian | genetic | walk_forward'),
    sa.Column('metric', sa.String(length=30), nullable=False, comment='优化目标: sharpe_ratio | total_return | calmar_ratio'),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('kline_interval', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('train_ratio', sa.Float(), nullable=False, comment='训练集比例'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total_combinations', sa.Integer(), nullable=False),
    sa.Column('completed_combinations', sa.Integer(), nullable=False),
    sa.Column('best_params', sa.Text(), nullable=True, comment='最优参数 (JSON)'),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('all_results', sa.Text(), nullable=True, comment='所有参数组合结果 (JSON)'),
    sa.Column('overfitting_warning', sa.Text(), nullable=True, comment='过拟合风险提示'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_param_optimization_tasks_status'), 'param_optimization_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_param_optimization_tasks_user_id'), 'param_optimization_tasks', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False, comment='方向: long | short'),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False, comment='持仓数量'),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False, comment='开仓均价'),
    sa.Column('mark_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='标记价格'),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='强平价格'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=True, comment='未实现盈亏'),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=False, comment='已实现盈亏'),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_mode', sa.String(length=20), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=24, scale=8), nullable=True, comment='占用保证金'),
    sa.Column('stop_loss_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='止损价'),
    sa.Column('take_profit_price', sa.Numeric(precision=24, scale=8), nullable=True, comment='止盈价'),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_open'), 'positions', ['is_open'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('definition', sa.Text(), nullable=False, comment='该版本定义快照'),
    sa.Column('change_summary', sa.String(length=500), nullable=True, comment='修改摘要'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='修改人用户 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('trading_accounts',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('total_equity_usdt', sa.Numeric(precision=24, scale=8), nullable=False, comment='总权益 (USDT)'),
    sa.Column('available_balance_usdt', sa.Numeric(precision=24, scale=8), nullable=False, comment='可用余额 (USDT)'),
    sa.Column('margin_used_usdt', sa.Numeric(precision=24, scale=8), nullable=False, comment='已用保证金 (USDT)'),
    sa.Column('unrealized_pnl_usdt', sa.Numeric(precision=24, scale=8), nullable=False, comment='未实现盈亏 (USDT)'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False, comment='同步时间'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_accounts_api_key_id'), 'trading_accounts', ['api_key_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False, comment='累计收益率(%)'),
    sa.Column('annual_return_pct', sa.Float(), nullable=False, comment='年化收益率(%)'),
    sa.Column('annual_volatility_pct', sa.Float(), nullable=False, comment='年化波动率(%)'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False, comment='夏普比率'),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False, comment='最大回撤(%)'),
    sa.Column('calmar_ratio', sa.Float(), nullable=False, comment='卡玛比率'),
    sa.Column('win_rate_pct', sa.Float(), nullable=False, comment='胜率(%)'),
    sa.Column('profit_loss_ratio', sa.Float(), nullable=False, comment='盈亏比'),
    sa.Column('avg_hold_hours', sa.Float(), nullable=False, comment='平均持仓时间(小时)'),
    sa.Column('total_trades', sa.Integer(), nullable=False, comment='总交易次数'),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=False, comment='最大连续亏损次数'),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=24, scale=8), nullable=False, comment='最终权益'),
    sa.Column('total_commission', sa.Numeric(precision=24, scale=8), nullable=False, comment='总手续费'),
    sa.Column('total_funding_fee', sa.Numeric(precision=24, scale=8), nullable=False, comment='总资金费率'),
    sa.Column('equity_curve', sa.Text(), nullable=True, comment='净值曲线 (JSON): [{time, equity}, ...]'),
    sa.Column('drawdown_curve', sa.Text(), nullable=True, comment='回撤曲线 (JSON)'),
    sa.Column('daily_returns', sa.Text(), nullable=True, comment='日收益率 (JSON)'),
    sa.Column('monthly_heatmap', sa.Text(), nullable=True, comment='月度收益热力图数据 (JSON)'),
    sa.Column('trades', sa.Text(), nullable=True, comment='交易明细 (JSON): [{entry_time, exit_time, symbol, side, entry_price, exit_price, amount, pnl, commission, ...}]'),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True, comment='基准(BTC)收益率(%)'),
    sa.Column('excess_return_pct', sa.Float(), nullable=True, comment='超额收益(%)'),
    sa.Column('beta', sa.Float(), nullable=True, comment='Beta'),
    sa.Column('information_ratio', sa.Float(), nullable=True, comment='信息比率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.ForeignKeyConstraint(['task_id'], ['backtest_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_task_id'), 'backtest_results', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_results_task_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_trading_accounts_api_key_id'), table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_open'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_param_optimization_tasks_user_id'), table_name='param_optimization_tasks')
    op.drop_index(op.f('ix_param_optimization_tasks_status'), table_name='param_optimization_tasks')
    op.drop_table('param_optimization_tasks')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtest_tasks_user_id'), table_name='backtest_tasks')
    op.drop_index(op.f('ix_backtest_tasks_strategy_id'), table_name='backtest_tasks')
    op.drop_index(op.f('ix_backtest_tasks_status'), table_name='backtest_tasks')
    op.drop_table('backtest_tasks')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_sim_trades_account_id'), table_name='sim_trades')
    op.drop_table('sim_trades')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    op.drop_index('idx_ticker_symbol_time', table_name='ticker_data')
    op.drop_table('ticker_data')
    op.drop_index(op.f('ix_sim_accounts_user_id'), table_name='sim_accounts')
    op.drop_table('sim_accounts')
    op.drop_table('roles')
    op.drop_index(op.f('ix_risk_rules_user_id'), table_name='risk_rules')
    op.drop_index(op.f('ix_risk_rules_strategy_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_strategy_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('idx_ob_snapshot_symbol_time', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_rules_user_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_strategy_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index('idx_klines_symbol_interval_time', table_name='klines')
    op.drop_index('idx_klines_exchange_symbol', table_name='klines')
    op.drop_table('klines')
    op.drop_index('idx_funding_symbol_time', table_name='funding_rates')
    op.drop_table('funding_rates')
    op.drop_index(op.f('ix_circuit_breakers_user_id'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_is_active'), table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
